//
//  CategoryViewModel.swift
//  SwiftUI-MVVM
//
//  Created by Rob Vander Sloot on 5/27/25.
//

import OSLog
import SwiftUI

final class CategoryViewModel: ViewModeling {
    @Published var state: CategoryViewState

    nonisolated static let jokeCount = 5
    private let session: any AppUrlSessionHandling

    /// Create a new instance.
    /// - Parameters:
    ///   - categoryName: The name of the joke category that drives the associated view's state.
    ///   - session: Injected URL session handler.
    init(categoryName: String, session: any AppUrlSessionHandling) {
        self.state = State(categoryName: categoryName)
        self.session = session

        fetchRandomJokes(for: categoryName)
    }

    // MARK: Events

    /// View-related events, typically generated by the view.
    enum Event {
        case refreshButtonPressed
    }

    func send(event: Event) {
        switch event {
        case .refreshButtonPressed:
            fetchRandomJokes(for: state.categoryName)
        }
    }
}

// MARK: - Private Helpers

private extension CategoryViewModel {
    func fetchRandomJokes(for category: String) {
        state.handleLoading()

        Task {
            let result: GetRandomJokesResult
            do {
                // fetch a set of random category jokes
                var jokes: [ChuckNorrisJoke] = []
                for _ in 0..<Self.jokeCount {
                    let jokeUrl = ChuckNorrisIoRequest.getRandomJoke(category: category).url
                    let joke: ChuckNorrisJoke = try await session.get(from: jokeUrl)

                    if !jokes.contains(where: { $0.value == joke.value }) {
                        jokes.append(joke)
                    }
                }

                result = GetRandomJokesResult.success(jokes)
            }
            catch let requestError as AppUrlSession.RequestError {
                result = GetRandomJokesResult.failure(requestError)
            }
            catch {
                result = GetRandomJokesResult.failure(AppUrlSession.RequestError.unexpected(error.localizedDescription))
            }

            Logger.view.trace("Fetch result: \(String(describing: result))")
            state.handleRandomJokesResult(result)
        }
    }
}
